name: AUnit Tests

on: [push]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Setup
      run: |
        cd ..
        git clone https://github.com/bxparks/EpoxyDuino
        git clone https://github.com/bxparks/AUnit
        
    - name: Run tests
      run: |
          make -C tests
          make -C tests runtests