name: AUnit Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup
      run: |
        cd ..
        git clone https://github.com/bxparks/EpoxyDuino
        git clone https://github.com/bxparks/AUnit
        
    - name: Run tests
      run: |
        make -C tests/driver_tests
        /home/runner/work/esp32-water-irrigation/esp32-water-irrigation/tests/driver_tests/driver_tests.o