name: Arduino Project linter 

on:
  push:
    branches-ignore: [master, main]
    # Remove the line above to run when pushing to master or main
  pull_request:
    branches: [master, main]
  workflow_call:

jobs:
  lint:
    name: Arduino Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: arduino/arduino-lint-action@v1
        with:
          recursive: true 
          library-manager: update
          compliance: strict

      - shell: pwsh
        run: |
          git diff --name-only main

      - name: Run Super linter
        uses: super-linter/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: ${{ github.base_ref }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
