name: Arduino Project linter 

on:
  push:
  pull_request:
    branches: [master, main]
  workflow_call:

jobs:
  lint:
    name: Arduino Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: arduino/arduino-lint-action@v1
        with:
          recursive: true 
          library-manager: update
          compliance: strict

      - shell: pwsh
        run: |
          git fetch origin main:main
          git diff --name-only main

      - name: Run Super linter
        uses: super-linter/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: true
          # Think this conflicts with clang
          VALIDATE_CPP: false
          # for now we assume a basic branching strategy
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
