name: Arduino Project linter 

on:
  pull_request:
    branches: [master, main]
  workflow_call:

jobs:

  Super_linter:
     name: Super Lint
     runs-on: ubuntu-latest
     steps:
       - name: Fetch branch diff
       - shell: pwsh
         run: |
           git fetch origin main:main
           git diff --name-only main
       - name: Run Super Linter
         uses: super-linter/super-linter@v5     
         env:
           VALIDATE_ALL_CODEBASE: false
           # Think this conflicts with clang
           VALIDATE_CPP: false
           # for now we assume a basic branching strategy
           DEFAULT_BRANCH: ${{ github.base_ref }}
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         
  Arduino_linter:
    name: Arduino Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: arduino/arduino-lint-action@v1
        with:
          recursive: true 
          library-manager: update
          compliance: strict
  
  
          
